### PR TITLE
Re-write the main binding to use a proxy object to avoid global scope

### PR DESCRIPTION
**Pull request by ospfranco**
closes https://github.com/ospfranco/react-native-quick-sqlite/issues/59

@EduFrazao would you mind taking a look and doing a quick test?

### CODE REVIEW

**Comment by ospfranco** [comment]
I also changed how the module was initialized by using a blocking synchronous method, hopefully that will take care of the bindings failing to install every once in a while (after simulator reload for example)

**Comment by EduFrazao** [comment]
> closes #59
> 
> @EduFrazao would you mind taking a look and doing a quick test?

Hi @ospfranco .. Sure, I will do that tonight!

**Comment by ospfranco** [comment]
Everything is stable, I will release it now and you can do a test later! thanks!

**Comment by EduFrazao** [comment]
> Everything looks stable to me, I will release it now and you can do a test later! thanks!

@ospfranco Hi. Sorry for the late response.
Everything seems stable here too. I've made tests with the new QuickSQLite and with IDBConnection (that I use most).

I have a doubt: My project is TypeScript, so my lint reads index.d.ts from lib/typescript. I fixed this file with this new changes, but I noted that this file folder is in the git ignore list. Is this correct?

**Comment by EduFrazao** [comment]
> > Everything looks stable to me, I will release it now and you can do a test later! thanks!
> 
> @ospfranco Hi. Sorry for the late response. Everything seems stable here too. I've made tests with the new QuickSQLite and with IDBConnection (that I use most).
> 
> I have a doubt: My project is TypeScript, so my lint reads index.d.ts from lib/typescript. I fixed this file with this new changes, but I noted that this file folder is in the git ignore list. Is this correct?

@ospfranco Please, disconsider this doubt. I've noted that this file is auto-generated when attached to the consumer project.
I'm already running the 4.0 version here!
Everything seems fine!

**Comment by ospfranco** [comment]
I don't quite understand what you mean, but please do open a new issue with more details

**Comment by EduFrazao** [comment]
> I don't quite understand what you mean, but please do open a new issue with more details

It's not a issue. I was thinking that the index.d.ts must be manually updated, but this file is auto-generated. So, there is no need to change anything on the 4.0 release.
Everything seems to work fine with QuickSQLite and with IDBConnection.

Thank you for your effort!

**Pull request merged**
