### PR TITLE
Refactor to promise based and easier APIs

### PR DESCRIPTION
**Pull request by ospfranco**
I was using raw queries the other day and realized it is kinda awkward to use some of the methods. Also the fact that devs are using the TypeORM wrapper bothers me. I've refactored the code to throw errors (no point in fighting the JS patterns) which makes the code and APIs a bit easier to read/understand. This is however a major refactoring. @EduFrazao would you be willing to give a hand to test this changes?

### CODE REVIEW

**Comment by EduFrazao** [comment]
> I was using raw queries the other day and realized it is kinda awkward to use some of the methods. Also the fact that devs are using the TypeORM wrapper bothers me. I've refactored the code to throw errors (no point in fighting the JS patterns) which makes the code and APIs a bit easier to read/understand. This is however a major refactoring. @EduFrazao would you be willing to give a hand to test this changes?

Hi @ospfranco!
Yesterday I try to upgrade SQLite to 3.39.4, but I can't build from the main branch. I got some errors on CMakeLists (pointing to files that was renamed, etc). I suppose that you are in the middle of some changes. I saw new functions everywhere :).

I will pull your new changes and try again. Thanks for your effort!

**Comment by ospfranco** [comment]
Yeah, I was working on main, but I undid all my changes, you should be able to update now

**Comment by cmoel** [comment]
I forked this repo to build a similar Promise-based interface and was planning to open issue to ask about the appetite for a PR 😅 It looks like you beat me to it! ❤️

**Comment by ospfranco** [comment]
@cmoel feel free to contribute by helping testing the changes :)

**Comment by ospfranco** [comment]
@cmoel @EduFrazao any chance to try it yet?

**Comment by cmoel** [comment]
@ospfranco I haven't had a chance to test yet, no and I'm not sure when I will. I fruitlessly spent some time trying to upgrade the example app to react-native 0.71.2.

**Comment by EduFrazao** [comment]
@ospfranco 
I'm trying to build from the refactor branch, but I got this error:

```
  CMake Error at CMakeLists.txt:39 (add_library):
    Cannot find source file:
  
      ../cpp/installer.cpp
  
    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
    .hpp .hxx .in .txx
  
  
  CMake Error at CMakeLists.txt:39 (add_library):
    No SOURCES given to target: react-native-quick-sqlite

```

Are you able to build for android right now?
I belive that "installer" was renamed to "bindings", on "osp" namespace right?

**Comment by EduFrazao** [comment]
I've made some changes, listing the new files on CMakeLists.txt and changing the ```cpp-adapter.cpp``` to import the correct bindings source. Source compiles, but I got an crash registering the host functions:

image

**Comment by ospfranco** [comment]
Ah didn't test android, yeah, probably some changes broke there.

**Comment by EduFrazao** [comment]
> Android compiles and runs now
 
Now it builds, but still crashing here. The crash appears to be on file bindings.cpp, line 212, at least this line is reported in the crash log.

```
auto promiseCtr = rt.global().getPropertyAsFunction(rt, "Promise");
```
[crash.txt](https://github.com/ospfranco/react-native-quick-sqlite/files/9727649/crash.txt)

**Comment by ospfranco** [comment]
Added the loadFile and loadFileAsync methods, but I cannot reproduce the crash when calling the executeAsync method, it is working fine for me.

**Comment by ospfranco** [comment]
Tested on a real device and it is working there as well

**Comment by EduFrazao** [comment]
> Added the loadFile and loadFileAsync methods, but I cannot reproduce the crash when calling the executeAsync method, it is working fine for me.

I'ts strange. The crash occours with the new exposed "open" function.

**Comment by EduFrazao** [comment]
> Tested on a real device and it is working there as well

Really strange. I've made a full cleanup but crashes everytime when I try to open a connection.
What RN version are you using? Do you see any problems with the 0.69.x?

**Comment by EduFrazao** [comment]
@ospfranco
I've made something here and now I'm able to build. Instead of add a local clone of your project (yarn add file:///home...)
I've added directly the repository url + branch.

For now, only one error:

```
 "[react-native-quick-sqlite][asyncloadFile] The callback argument must be a function"
```
Basic operations like async transactions, async executions, open, close and attach are working.

**Comment by ospfranco** [comment]
I'm only using the example project inside the app. I will take care of the loadFileASync now. Thanks!

**Comment by EduFrazao** [comment]
Very nice refactory.
I like the new API. Semantic and clean.

**Pull request merged**
