### PR TITLE
Android cpp-adatapter refactory

### PR DESCRIPTION
**Pull request by EduFrazao**
- Using fbjni to get access on jsCallInvoker
     - loadSQLFile refactores to allow reuse
     - Added asyncLoadSQLFile

### CODE REVIEW

**Comment by EduFrazao** [comment]
Hi @ospfranco .
I have sucefully tested this branch with android 11, on a real device and also on emulator.
Background thread is working, and invoking callbacks too.

**Comment by ospfranco** [comment]
I tried to reproduce your changes on my branch and somehow it is crashing for me

**Comment by EduFrazao** [comment]
> I tried to reproduce your changes on my branch and somehow it is crashing for me, would you mind taking a look?
Sure, I will fetch your changes and try here. I just have something to do right now, and I will be able to test in about 1 hour!

**Comment by ospfranco** [comment]
I just had the strangest thing happen, I checked out your branch compiled it and the app was still crashing, deleted the app from the emulator and re-installed and it worked. Then did the same with my branch changes and now it works... ugh android... in any case... I will copy your changes into my branch since I renamed a bunch of stuff to make it more understandable, but the iOS side also needs to be adjusted

**Comment by ospfranco** [comment]
I'm going to close this pull request but I copied all your changes @EduFrazao into https://github.com/ospfranco/react-native-quick-sqlite/pull/29

I modified the code on iOS for it to pass the jsCallInvoker but somehow it is crashing, so still need to fix that :)

**Comment by EduFrazao** [comment]
> I just had the strangest thing happen, I checked out your branch compiled it and the app was still crashing, deleted the app from the emulator and re-installed and it worked. Then did the same with my branch changes and now it works... ugh android... in any case... I will copy your changes into my branch since I renamed a bunch of stuff to make it more understandable, but the iOS side also needs to be adjusted

Ouch. Really strange, but i'm really glad that now its working :).
Very nice!

**Pull request closed without merging**
