### PR TITLE
Added a native method to provide transactional batch execution.

### PR DESCRIPTION
**Pull request by EduFrazao**
The idea is to avoid to many JSI Calls for large operations.

### CODE REVIEW

**Comment by ospfranco** [comment]
If I remember correctly the first batch method I wrote took a large array of different operations, your approach kinda flips it and takes one operation with different params... not 100% sure if that is really useful, it does solve your problem, but might be kinda niche.

I guess the best of both worlds would be to accept both types, passing different operations and different params. That being said, I really wonder if this will be needed in the long term, doubt many will use the low-level APIs directly.

**Comment by EduFrazao** [comment]
Hi @ospfranco.
This bulk method accept in fact, three kind of parameters.

Its possible to use something like:

```
const params = [];
params.push(['INSERT INTO A VALUES (1)']);
params.push(['INSERT INTO B VALUES (?)', [1]]);
params.push(['INSERT INTO C VALUES (?)', [2]]);
params.push(['INSERT INTO D VALUES (?)', [3]]);
params.push(['INSERT INTO E VALUES (?, ?)', [0, 1]]);
params.push(['INSERT INTO F VALUES (?, ?)', [[0, 1],[2, 3],[4, 5]]);
sqlite.executeSqlBatch('dbName', params);
```

They will be all valid. My idea is to allow some scenarios where users must use the same insert/update, with many different params, in a effort to reduce the memory consumption of parameter copy? Do you think that it would be useful?

**Comment by ospfranco** [comment]
ah, ok, then I misunderstood the code, this is great. Can you update the README as well?

**Comment by EduFrazao** [comment]
> ah, ok, then I misunderstood the code, this is great. Can you update the README as well?
Nice. Sure, I will update the Readme and send another commit. Thanks.

**Comment by EduFrazao** [comment]
@ospfranco README changed. Please let me know if you want to more examples on it.

**Comment by ospfranco** [comment]
I merged, but I just realized the batch execution method only takes one callback? what happens when it errors out?

**Comment by ospfranco** [comment]
also I saw you are throwing errors, inside the `execSQLBatch` method, I moved away from throwing errors because it would crash typeORM so I think it is better to keep the behavior consistent

**Comment by EduFrazao** [comment]
> I merged, but I just realized the batch execution method only takes one callback? what happens when it errors out?

On errors it will rollback the transaction and the callback will contain the standard error output:

```
{
status: 1
message: 'SQLite error message'
}
```
Do you think that this is acceptable?

**Comment by EduFrazao** [comment]
About thowing errors, I really do that on parameter validation.
If you want, I can refactor to calling the callback with standard error
output like

{
status: 1,
message: '[react-native-quick-sqlite][execSQLBatch] - No SQL Commands found'
}

Do you prefer that way?

Eduardo Frazão

**Pull request merged**
