### PR TITLE
add custom function and aggregates

### PR DESCRIPTION
**Pull request by oceanwap**
This PR aims to add custom function and aggregate support to react-native-quick-sqlite.

1. adds function API to add custom functions.
2. adds aggregate API to add custom aggregate functions
3. adds test cases for functions and aggregate functions.

@ospfranco Please check this PR.

### CODE REVIEW

**Comment by ospfranco** [comment]
A lot of code to review, took a quick look some high level points:

- Do not aggregate the jsi namespace, the symbols inside are too generic and easy to clash/mix
- please stick to the namespace I was using, I think it was osp or something like that
- There are some mismatches of the RN version, also why update it?
- You modified the flag check on install index.ts, why?

It would also help to get a high level description of the changes, the motivation... there is a lot of code, so I might not get to review this any time soon

**Comment by oceanwap** [comment]
> * Do not aggregate the jsi namespace, the symbols inside are too generic and easy to clash/mix
Fixed.

> * please stick to the namespace I was using, I think it was osp or something like that
Fixed. using osp namespace in both classes.

> * There are some mismatches of the RN version, also why update it?
rolled back to previous version.

> * You modified the flag check on install index.ts, why?
rolled back that change. It was giving type error using void return value.

**Comment by ospfranco** [comment]
The problem is that jsi::Value is not really part of the C++ context, but rather part of the javascript virtual machine, which means they can be de-allocated and your functions needs to long-live after the JS calling function has been cleaned... they also don't have any built in copy semantics afaik. At least in my experience it is better to turn everything into C++ values and just store those.

**Comment by oceanwap** [comment]
@ospfranco I also have same understanding. But the problem is that we can't fix a value type and they can change as well. For example, a javascript function can change value type itself.
If converting them is an option then probably my solution is slightly better if not much. May be you will have some ideas once you have reviewed it completely.

**Comment by ospfranco** [comment]
There is already a wrapping C++ class somewhere in the code, you should use that, also... no, no Discord, don't have time to maintain it

**Comment by ospfranco** [comment]
Here is a discord server we can use to chat

https://discord.gg/6xnbhEyT

**Pull request closed without merging**
